### ISSUE TITLE
Errors when building Jekyll site

### ISSUE THREAD

**Issue by ghost** [alfanick/jekyll-related-posts#2]
Hi --

This looks like an interesting plugin, but I'm having some trouble getting it to run. If I enable the plugin in _config.yml and then build the site, it gives an error:

`Jekyll 3.1.2 | Error:  Is a directory @ io_fread - [...]/jekyllsite/_site/1998/11/my-first-post/`

That's in the published _site folder. My permalink format is /:year/:month/:title/

If I use the max_count option and set it to 3, then the build has a different error:

`jekyll 3.1.2 | Error:  no implicit conversion of Array into Hash`

Also, there's a message when building: [Deprecated!] Use WhitespaceTokenizer instead.

**Comment by eduards** [comment]
Hi, unfortunately I get exactly the same error...

**Comment by jeff-pang** [comment]
Any solution to this?

**Comment by alfanick** [comment]
hey, I will fix this today

**Comment by alfanick** [comment]
Can someone post their _config.yml and ruby version? I am struggling to reproduce the error.

**Comment by alfanick** [comment]
just fixed the issue, please update [jekyll-related-posts](https://rubygems.org/gems/jekyll-related-posts) gem to 0.1.2
